// This file is auto-generated by `pnpm db:types`
// Run that command after making schema changes to update these types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          avatar_url: string | null;
          onboarding_completed: boolean;
          onboarding_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          onboarding_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          onboarding_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          muscle_groups: Database['public']['Enums']['muscle_group'][];
          equipment: Database['public']['Enums']['equipment_type'][];
          instructions: string[] | null;
          exercise_type: Database['public']['Enums']['exercise_type'];
          is_custom: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          muscle_groups?: Database['public']['Enums']['muscle_group'][];
          equipment?: Database['public']['Enums']['equipment_type'][];
          instructions?: string[] | null;
          exercise_type?: Database['public']['Enums']['exercise_type'];
          is_custom?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          muscle_groups?: Database['public']['Enums']['muscle_group'][];
          equipment?: Database['public']['Enums']['equipment_type'][];
          instructions?: string[] | null;
          exercise_type?: Database['public']['Enums']['exercise_type'];
          is_custom?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      programs: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          duration_weeks: number;
          days_per_week: number;
          difficulty: Database['public']['Enums']['difficulty_level'];
          goal: Database['public']['Enums']['program_goal'];
          equipment: Database['public']['Enums']['equipment_type'][];
          is_template: boolean;
          is_public: boolean;
          is_premium: boolean;
          user_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          duration_weeks: number;
          days_per_week: number;
          difficulty: Database['public']['Enums']['difficulty_level'];
          goal: Database['public']['Enums']['program_goal'];
          equipment?: Database['public']['Enums']['equipment_type'][];
          is_template?: boolean;
          is_public?: boolean;
          is_premium?: boolean;
          user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          duration_weeks?: number;
          days_per_week?: number;
          difficulty?: Database['public']['Enums']['difficulty_level'];
          goal?: Database['public']['Enums']['program_goal'];
          equipment?: Database['public']['Enums']['equipment_type'][];
          is_template?: boolean;
          is_public?: boolean;
          is_premium?: boolean;
          user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      workouts: {
        Row: {
          id: string;
          program_id: string;
          name: string;
          day_of_week: number;
          week_number: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          name: string;
          day_of_week: number;
          week_number: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          name?: string;
          day_of_week?: number;
          week_number?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      workout_exercises: {
        Row: {
          id: string;
          workout_id: string;
          exercise_id: string;
          sort_order: number;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workout_id: string;
          exercise_id: string;
          sort_order?: number;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workout_id?: string;
          exercise_id?: string;
          sort_order?: number;
          notes?: string | null;
          created_at?: string;
        };
      };
      exercise_sets: {
        Row: {
          id: string;
          workout_exercise_id: string;
          set_number: number;
          target_reps: number;
          target_weight: number | null;
          target_duration_seconds: number | null;
          target_distance_meters: number | null;
          rest_seconds: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          workout_exercise_id: string;
          set_number: number;
          target_reps: number;
          target_weight?: number | null;
          target_duration_seconds?: number | null;
          target_distance_meters?: number | null;
          rest_seconds?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          workout_exercise_id?: string;
          set_number?: number;
          target_reps?: number;
          target_weight?: number | null;
          target_duration_seconds?: number | null;
          target_distance_meters?: number | null;
          rest_seconds?: number;
          created_at?: string;
        };
      };
      workout_logs: {
        Row: {
          id: string;
          user_id: string;
          workout_id: string;
          program_id: string | null;
          started_at: string;
          completed_at: string | null;
          duration_seconds: number | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          workout_id: string;
          program_id?: string | null;
          started_at?: string;
          completed_at?: string | null;
          duration_seconds?: number | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          workout_id?: string;
          program_id?: string | null;
          started_at?: string;
          completed_at?: string | null;
          duration_seconds?: number | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      set_logs: {
        Row: {
          id: string;
          workout_log_id: string;
          exercise_set_id: string;
          exercise_id: string;
          actual_reps: number;
          actual_weight: number;
          actual_duration_seconds: number | null;
          actual_distance_meters: number | null;
          rpe: number | null;
          completed_at: string;
        };
        Insert: {
          id?: string;
          workout_log_id: string;
          exercise_set_id: string;
          exercise_id: string;
          actual_reps: number;
          actual_weight?: number;
          actual_duration_seconds?: number | null;
          actual_distance_meters?: number | null;
          rpe?: number | null;
          completed_at?: string;
        };
        Update: {
          id?: string;
          workout_log_id?: string;
          exercise_set_id?: string;
          exercise_id?: string;
          actual_reps?: number;
          actual_weight?: number;
          actual_duration_seconds?: number | null;
          actual_distance_meters?: number | null;
          rpe?: number | null;
          completed_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          status: Database['public']['Enums']['subscription_status'];
          plan: Database['public']['Enums']['subscription_plan'];
          provider: Database['public']['Enums']['subscription_provider'];
          provider_subscription_id: string | null;
          provider_customer_id: string | null;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          status?: Database['public']['Enums']['subscription_status'];
          plan?: Database['public']['Enums']['subscription_plan'];
          provider: Database['public']['Enums']['subscription_provider'];
          provider_subscription_id?: string | null;
          provider_customer_id?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          status?: Database['public']['Enums']['subscription_status'];
          plan?: Database['public']['Enums']['subscription_plan'];
          provider?: Database['public']['Enums']['subscription_provider'];
          provider_subscription_id?: string | null;
          provider_customer_id?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          description: string | null;
          discount_percent: number | null;
          discount_months: number | null;
          grants_lifetime: boolean;
          max_uses: number | null;
          times_used: number;
          valid_from: string | null;
          valid_until: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          description?: string | null;
          discount_percent?: number | null;
          discount_months?: number | null;
          grants_lifetime?: boolean;
          max_uses?: number | null;
          times_used?: number;
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          description?: string | null;
          discount_percent?: number | null;
          discount_months?: number | null;
          grants_lifetime?: boolean;
          max_uses?: number | null;
          times_used?: number;
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      coupon_redemptions: {
        Row: {
          id: string;
          coupon_id: string;
          user_id: string;
          redeemed_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          user_id: string;
          redeemed_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          user_id?: string;
          redeemed_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          admin_id: string;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          admin_id: string;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          admin_id?: string;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      user_programs: {
        Row: {
          id: string;
          user_id: string;
          program_id: string;
          status: Database['public']['Enums']['program_status'];
          started_at: string;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          program_id: string;
          status?: Database['public']['Enums']['program_status'];
          started_at?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          program_id?: string;
          status?: Database['public']['Enums']['program_status'];
          started_at?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {
      has_premium_access: {
        Args: { check_user_id: string };
        Returns: boolean;
      };
      redeem_coupon: {
        Args: { coupon_code: string };
        Returns: Json;
      };
      copy_program_to_user: {
        Args: { template_program_id: string };
        Returns: string;
      };
      start_program: {
        Args: { p_program_id: string };
        Returns: Json;
      };
      get_active_program: {
        Args: Record<string, never>;
        Returns: Json;
      };
      complete_active_program: {
        Args: Record<string, never>;
        Returns: Json;
      };
    };
    Enums: {
      difficulty_level: 'beginner' | 'intermediate' | 'advanced';
      program_goal: 'strength' | 'hypertrophy' | 'endurance' | 'general';
      muscle_group:
        | 'chest'
        | 'back'
        | 'shoulders'
        | 'biceps'
        | 'triceps'
        | 'forearms'
        | 'abs'
        | 'obliques'
        | 'quads'
        | 'hamstrings'
        | 'glutes'
        | 'calves'
        | 'traps'
        | 'lats';
      equipment_type:
        | 'barbell'
        | 'dumbbell'
        | 'kettlebell'
        | 'cable'
        | 'machine'
        | 'bodyweight'
        | 'resistance_band'
        | 'bench'
        | 'pull_up_bar'
        | 'none';
      exercise_type: 'strength' | 'cardio' | 'flexibility' | 'other';
      subscription_status: 'active' | 'cancelled' | 'expired' | 'trial';
      subscription_plan: 'free' | 'premium' | 'lifetime';
      subscription_provider: 'apple' | 'google' | 'stripe' | 'manual';
      program_status: 'active' | 'paused' | 'completed';
    };
  };
};

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T];

// Convenience type aliases
export type Profile = Tables<'profiles'>;
export type Exercise = Tables<'exercises'>;
export type Program = Tables<'programs'>;
export type Workout = Tables<'workouts'>;
export type WorkoutExercise = Tables<'workout_exercises'>;
export type ExerciseSet = Tables<'exercise_sets'>;
export type WorkoutLog = Tables<'workout_logs'>;
export type SetLog = Tables<'set_logs'>;
export type Subscription = Tables<'subscriptions'>;
export type Coupon = Tables<'coupons'>;
export type CouponRedemption = Tables<'coupon_redemptions'>;
export type AuditLog = Tables<'audit_log'>;
export type UserProgram = Tables<'user_programs'>;

// Enum type aliases
export type DifficultyLevel = Enums<'difficulty_level'>;
export type ProgramGoal = Enums<'program_goal'>;
export type MuscleGroup = Enums<'muscle_group'>;
export type EquipmentType = Enums<'equipment_type'>;
export type SubscriptionStatus = Enums<'subscription_status'>;
export type SubscriptionPlan = Enums<'subscription_plan'>;
export type SubscriptionProvider = Enums<'subscription_provider'>;
export type ProgramStatus = Enums<'program_status'>;
